# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acf3f9f89242bac3890c432ded6c08d04c7b51dbff2188f6fb09169a14b84337e812738c86a7cd170ac610127dc6c14fb4ccf7be5a10a218c719926ee3ddf2e9

test:
  secret_key_base: bf334814dcaab7127d25b78ac9f928d836ef52c424c68a024723444d8b9ba86a2a8a551f0774d6b14e36bc57a8328f107f8f2bd72b19bd04450e3d7a5a08736a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
